### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by cristinaITdeveloper** [kevinsawicki/http-request#130]
Hi! I use your library, nice! I have a crash. This is the stack trace:
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 42 byte allocation with 0 free bytes and 3GB until OOM
       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
       at com.android.okhttp.okio.Buffer.readString(Buffer.java:582)
       at com.android.okhttp.okio.Buffer.readUtf8(Buffer.java:557)
       at com.android.okhttp.okio.Buffer.readUtf8Line(Buffer.java:618)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:203)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:194)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java)
       at com.github.kevinsawicki.http.HttpRequest.header(SourceFile:2114)
       at com.github.kevinsawicki.http.HttpRequest.parameter(SourceFile:2209)
       at com.github.kevinsawicki.http.HttpRequest.charset(SourceFile:2319)
       at com.github.kevinsawicki.http.HttpRequest.body(SourceFile:1779)
       at com.hexlab.sokhrates.fragment.binding.FragmentListBinding$5.call(SourceFile:169)
       at com.hexlab.sokhrates.fragment.binding.FragmentListBinding$5.call(SourceFile:164)
       at bolts.Task$4.run(SourceFile:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by YangLzy** [comment]
+1,i meet this issue angin!

**Comment by Gybra** [comment]
@YangLzy Instead of .body() use the stream reader from this library and you solved the issue, then use gson and pass the reader obtained to it. And you're good to go
